#packages\erp_repository\pubspec.yaml
name: erp_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.1

# Add regular dependencies here.
dependencies:
  cloud_storage_api:
    path: ../cloud_storage_api
  file_picker: ^10.3.10
  local_storage_api:
    path: ../local_storage_api
  # path: ^1.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
